#!/usr/bin/env bash

set -euo pipefail

[[ $# -eq 6 ]] || exit 4
[[ $1 == -fsS ]] || exit 4
[[ $2 == --max-time && $3 == 5 ]] || exit 4
[[ $4 == --max-filesize && $5 == 65536 ]] || exit 4
url=$6
[[ $url == https://geocoding-api.open-meteo.com/* ]] || exit 2
[[ $url == *language=de* ]] || exit 3

printf '%s\n' '{"results":[{"name":"Berlin","admin1":"Berlin","country":"Deutschland","feature_code":"PPLC","country_code":"DE","latitude":52.52,"longitude":13.405},{"name":"Bernau bei Berlin","admin1":"Brandenburg","country":"Deutschland","feature_code":"PPL","country_code":"DE","latitude":52.6798,"longitude":13.5871}]}'
